import type { Metadata } from "next";
import { NotoSansJp } from "./utils/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="ja">
      <body className={`${NotoSansJp.className}`}>{children}</body>
    </html>
  );
}
